DROP TABLE IF EXISTS `mp_orders`;
CREATE TABLE `mp_orders` (
  `order_number` int(11) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) NOT NULL,
  `user_profile_uuid` varchar(36) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `address` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `unit_uuid` varchar(36) DEFAULT NULL,
  `residence_uuid` varchar(36) DEFAULT NULL,
  `school_year_id` int(11) unsigned DEFAULT NULL,
  `school_term_id` int(10) unsigned DEFAULT NULL,
  `student_uuid` varchar(36) DEFAULT NULL,
  `store_uuid` varchar(36) DEFAULT NULL,
  `total_amount` decimal(10,2) DEFAULT NULL,
  `total_amount_cents` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `currency` varchar(50) DEFAULT 'RM',
  `status` varchar(50) DEFAULT NULL,
  `payment_status` varchar(50) DEFAULT NULL,
  `paid_at` timestamp NULL DEFAULT NULL,
  `transaction_id` varchar(100) DEFAULT NULL,
  `pay_by` varchar(100) DEFAULT NULL,
  `checked_out_at` timestamp NULL DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `category_type_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`uuid`) USING BTREE,
  UNIQUE KEY `order_number` (`order_number`),
  KEY `fk_mp_orders_user_profile_uuid_user_profiles_uuid` (`user_profile_uuid`) USING BTREE,
  KEY `fk_mp_orders_residence_uuid_residences_uuid` (`residence_uuid`) USING BTREE,
  KEY `fk_mp_orders_unit_uuid_residence_units_uuid` (`unit_uuid`) USING BTREE,
  KEY `FK_mp_orders_school_years` (`school_year_id`),
  KEY `FK_mp_orders_school_terms` (`school_term_id`),
  KEY `FK_mp_orders_students` (`student_uuid`),
  KEY `FK_mp_orders_mp_stores` (`store_uuid`),
  CONSTRAINT `FK_mp_orders_mp_stores` FOREIGN KEY (`store_uuid`) REFERENCES `mp_stores` (`uuid`),
  CONSTRAINT `FK_mp_orders_school_terms` FOREIGN KEY (`school_term_id`) REFERENCES `school_terms` (`id`),
  CONSTRAINT `FK_mp_orders_school_years` FOREIGN KEY (`school_year_id`) REFERENCES `school_years` (`id`),
  CONSTRAINT `FK_mp_orders_students` FOREIGN KEY (`student_uuid`) REFERENCES `students` (`uuid`),
  CONSTRAINT `fk_mp_orders_residence_uuid_residences_uuid` FOREIGN KEY (`residence_uuid`) REFERENCES `residences` (`uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_mp_orders_unit_uuid_residence_units_uuid` FOREIGN KEY (`unit_uuid`) REFERENCES `residence_units` (`uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_mp_orders_user_profile_uuid_user_profiles_uuid` FOREIGN KEY (`user_profile_uuid`) REFERENCES `user_profiles` (`uuid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1020481836 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;