CREATE TABLE `user_profiles` (
  `uuid` varchar(36) NOT NULL,
  `name` varchar(500) CHARACTER SET utf8 DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `office_email` varchar(255) DEFAULT NULL,
  `phone_country_code` varchar(36) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `alt_country_code` varchar(36) DEFAULT NULL,
  `office_phone` varchar(255) DEFAULT NULL,
  `photo_url` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL,
  `photo` varchar(36) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `first_login_at` timestamp NULL DEFAULT NULL,
  `old_phone` varchar(255) DEFAULT NULL,
  `is_group_admin` tinyint(1) DEFAULT '0',
  `is_demo_account` tinyint(1) DEFAULT '0',
  `qr_code` varchar(255) DEFAULT NULL,
  `qrcode_expired_at` timestamp NULL DEFAULT NULL,
  `qrcode_updated_at` timestamp NULL DEFAULT NULL,
  `user_profile_id` int(11) NOT NULL AUTO_INCREMENT,
  `should_migrate` varchar(3) DEFAULT '000',
  `ums_token_status` varchar(3) DEFAULT '000',
  `migration_status` varchar(3) DEFAULT '000',
  `migrated_phone` varchar(255) DEFAULT NULL,
  `kb_token` text,
  `kb_refresh_token` text,
  PRIMARY KEY (`uuid`),
  KEY `photo` (`photo`),
  KEY `user_profile_id` (`user_profile_id`)
) ENGINE=InnoDB AUTO_INCREMENT=115251 DEFAULT CHARSET=latin1;