// Code generated by "tools"; DO NOT EDIT
package client_gkspg

//
type ChannelRecordStatData struct {
	RecordTime   string `json:"record_time"`   //
	ResponseTime int64  `json:"response_time"` // ResponseTime payment average response time , unit millisecond
	SuccessRate  int64  `json:"success_rate"`  // SuccessRate success rate
	TotalAmount  int64  `json:"total_amount"`  // TotalAmount total amount in the range
	TotalOrder   int64  `json:"total_order"`   // TotalOrder total order in the range
	Channel      string `json:"channel"`       //
	ModeOfPay    string `json:"mode_of_pay"`   //
}

//
type MerchantWalletInfoReq struct {
	MerchantId int64 `json:"merchant_id"` //
}

//
type WithdrawalListReq struct {
	PageSize  int64  `json:"page_size"`  //
	StartTime string `json:"start_time"` //
	Status    int64  `json:"status"`     //
	UserId    int64  `json:"user_id"`    //
	ClientId  int64  `json:"client_id"`  //
	EndTime   string `json:"end_time"`   //
	OrderNo   string `json:"order_no"`   //
	PageNo    int64  `json:"page_no"`    //
}

//
type TransactionListReq struct {
	Type            string `json:"type"`              // TP:topup, PAY:payment, TF:transfer, RF:refund, WD:withdrawal
	UserId          int64  `json:"user_id"`           //
	EndTime         string `json:"end_time"`          //
	MerchantOrderNo string `json:"merchant_order_no"` // merchant order no
	OrderNo         string `json:"order_no"`          //
	PageNo          int64  `json:"page_no"`           //
	PageSize        int64  `json:"page_size"`         //
	StartTime       string `json:"start_time"`        //
	ClientId        int64  `json:"client_id"`         //
	MerchantId      int64  `json:"merchant_id"`       //
}

//
type BaseResponseData struct {
}

//
type BaseResponse struct {
	Msg  string           `json:"msg"`  //
	Time int64            `json:"time"` //
	Code int64            `json:"code"` //
	Data BaseResponseData `json:"data"` //
}

//
type CcCardListReq struct {
	ClientId int64 `json:"client_id"` //
	UserId   int64 `json:"user_id"`   //
}

//
type MerchantWalletInfoRsp struct {
	PrefundBalance   int64 `json:"prefund_balance"`   // prefund余额
	SettledBalance   int64 `json:"settled_balance"`   // 已结算余额
	UnsettledBalance int64 `json:"unsettled_balance"` // 未结算余额
}

//
type PrefundInfo struct {
	UserId int64 `json:"user_id"` //
	Status int64 `json:"status"`  // 1 suc 2 fail
}

//
type PrefundRecordsDetail struct {
	Amount       int64  `json:"amount"`        // Amount prefund 金额
	MerchantId   string `json:"merchant_id"`   // MerchantID 商户编号/merchant id
	OrderSn      string `json:"order_sn"`      // OrderSn 用户订单号
	ReferenceId  string `json:"reference_id"`  // ReferenceID 参考编号/ change the amount reference no.
	RevertStatus int64  `json:"revert_status"` // RevertStatus revert 状态 1:unrevert 2:reverted
	UserId       int64  `json:"user_id"`       // UserID 用户id
	UserName     string `json:"user_name"`     // 用户名
}

//
type MerchantPayChannelItem struct {
	PayChannelName        string `json:"pay_channel_name"`        // 支付类型名称/pay channel name
	PayChannelSymbol      string `json:"pay_channel_symbol"`      // 支付符号简称/pay short symbol
	PayTypeId             int64  `json:"pay_type_id"`             // 支付类型Id /pay type id
	ProviderName          string `json:"provider_name"`           // 支付提供商/pay provider name
	Status                int64  `json:"status"`                  // 状态/status 1 active  2 close
	SuccessRate           int64  `json:"success_rate"`            //
	Weights               int64  `json:"weights"`                 // 权重/Weights
	PayChannelDescription string `json:"pay_channel_description"` // 支付类型描述/pay channel description
}

//
type CcTopUpRsp struct {
	Amount          string `json:"amount"`            //
	MerchantOrderNo string `json:"merchant_order_no"` //
	OrderNo         string `json:"order_no"`          //
}

//
type PrefundResponseData struct {
	Results    []PrefundInfo `json:"results"`     //
	TotalMoney int64         `json:"total_money"` // just for success
}

//
type PrefundResponse struct {
	Data PrefundResponseData `json:"data"` //
}

//
type RefundApplyReq struct {
	RefundCardNo     string `json:"refund_card_no"`     // Bank card number of refund
	RefundHolderName string `json:"refund_holder_name"` // Name of refund cardholder
	WhoRefund        int64  `json:"who_refund"`         // 1 :user 2:merchant 3:platform
	MerchantId       int64  `json:"merchant_id"`        //
	MerchantOrderNo  string `json:"merchant_order_no"`  //
	RefundBankName   string `json:"refund_bank_name"`   // Name of refund bank
	ApplyAmount      string `json:"apply_amount"`       // refund partial amount  unit:cent
	ClientIp         string `json:"client_ip"`          //
	ReasonForRefund  string `json:"reason_for_refund"`  //
}

//
type TopUpMerchantReq struct {
	MerchantId int64  `json:"merchant_id"` //
	Amount     string `json:"amount"`      //
}

//
type TransferReq struct {
	Pin          string `json:"pin"`            //
	ToUserMobile string `json:"to_user_mobile"` //
	UserId       int64  `json:"user_id"`        //
	Amount       string `json:"amount"`         //
	ClientId     int64  `json:"client_id"`      //
	ClientIp     string `json:"client_ip"`      //
	Description  string `json:"description"`    //
}

//
type OfflineDepositListData struct {
	Amount     int64  `json:"amount"`      //
	ChequeNo   string `json:"cheque_no"`   // 支票号  cheque no
	CreateTime string `json:"create_time"` //
	Id         int64  `json:"id"`          //
	Status     int64  `json:"status"`      // Status 1 :pending 2:approve 3:decline
	Type       int64  `json:"type"`        // Type 1 :credit 2 debit
	UserId     int64  `json:"user_id"`     //
}

//
type RefundListData struct {
	ReasonForRefund string `json:"reason_for_refund"` // ReasonForRefund 退款原因
	ApplyAmount     int64  `json:"apply_amount"`      // ApplyAmount 申请退款金额
	Id              int64  `json:"id"`                //
	MerchantOrderNo string `json:"merchant_order_no"` // MerchantOrderNo 关联的商户支付订单号
	OrderNo         string `json:"order_no"`          // OrderNo 退款订单编号
	PaymentOrderNo  string `json:"payment_order_no"`  // PaymentOrderNo 关联的支付系统订单号
	RefundType      string `json:"refund_type"`       // RefundType 退款方式 merchant表里面支持的支付通道枚举类型
	Status          int64  `json:"status"`            // Status 状态: 1:审核中 2:审核通过 3:已完成 4:拒绝  5:已取消
	TradeNo         string `json:"trade_no"`          // TradeNo  关联的交易流水号
	CreateTime      string `json:"create_time"`       //
	IsRefundFee     int64  `json:"is_refund_fee"`     // IsRefundFee 是否退回手续费 1:no 2:yes
	UserId          int64  `json:"user_id"`           //
	MerchantId      int64  `json:"merchant_id"`       //
	RefundFee       int64  `json:"refund_fee"`        // RefundFee 退款手续费
	UpdateTime      string `json:"update_time"`       //
	WhoRefund       int64  `json:"who_refund"`        // WhoRefund 谁发起退款请求 1 :user 2:merchant 3:platform
	ActualAmount    int64  `json:"actual_amount"`     // ActualAmount 批准退款金额
	IsAuto          int64  `json:"is_auto"`           // IsAuto 是否自动退款: 1:待定 2:手动  3:自动
}

//
type TopUpIndexReq struct {
	EndTime         string `json:"end_time"`          //
	MerchantId      int64  `json:"merchant_id"`       // MerchantID 商户号
	MerchantOrderNo string `json:"merchant_order_no"` // MerchantOrderNo 商户订单编号
	PageNo          int64  `json:"page_no"`           //
	StartTime       string `json:"start_time"`        //
	Status          int64  `json:"status"`            // Status 状态 :1 正在充值中 2:已完成 3:失败 4.已撤销
	UserId          int64  `json:"user_id"`           // UserID 用户id
	OrderNo         string `json:"order_no"`          // OrderNo 系统订单编号
	PageSize        int64  `json:"page_size"`         //
}

//
type TransactionListData struct {
	BankTime        string `json:"bank_time"`         // BankTime 银行实际交易时间
	ServeCharges    int64  `json:"serve_charges"`     // serve_charges 平台服务费
	Amount          int64  `json:"amount"`            // Amount 订单金额 单位分
	BankOrderNo     string `json:"bank_order_no"`     // BankOrderNo 银行订单流水号
	CreateTime      string `json:"create_time"`       // CreateTime
	ModeOfPay       string `json:"mode_of_pay"`       // ModeOfPayment ModeOfPayment 支付方式 merchant表里面支持的支付通道枚举类型
	TradeNo         string `json:"trade_no"`          // TradeNo 交易流水号
	WalletType      string `json:"wallet_type"`       // WalletType 钱包类型代号
	ActualAmount    int64  `json:"actual_amount"`     // ActualAmount 实际支付金额
	Fee             int64  `json:"fee"`               // Fee 手续费
	MerchantOrderNo string `json:"merchant_order_no"` // MerchantOrderNo 商户订单号
	OrderNo         string `json:"order_no"`          // OrderNo 系统订单号
	Type            string `json:"type"`              // Type 交易类型 topup,payment,withdrawal等的简称
	BankAmount      int64  `json:"bank_amount"`       // BankAmount 银行返回的交易金额
	ClientId        int64  `json:"client_id"`         // ClientID 主商户id
	MerchantId      int64  `json:"merchant_id"`       // MerchantID 商户号
	TradeTime       string `json:"trade_time"`        // TradeTime 用户发起交易时间
	UserId          int64  `json:"user_id"`           // UserID 用户id
	BankCode        string `json:"bank_code"`         // BankCode 银行简称代码
}

//
type OfflineDepositAuditReq struct {
	Id     int64 `json:"id"`     //
	Status int64 `json:"status"` // Status 1 :pending 2:approve 3:decline
}

//
type WithdrawalApplyReq struct {
	ClientIp              string `json:"client_ip"`               //
	PayeeBankName         string `json:"payee_bank_name"`         //
	PayeeIdentificationId string `json:"payee_identification_id"` //
	PayeeName             string `json:"payee_name"`              //
	ClientId              int64  `json:"client_id"`               //
	Description           string `json:"description"`             //
	Mobile                string `json:"mobile"`                  //
	PayeeBankAccountNo    string `json:"payee_bank_account_no"`   //
	Reason                string `json:"reason"`                  //
}

//
type CcAddCardReq struct {
	ClientId  int64  `json:"client_id"`  //
	NotifyUrl string `json:"notify_url"` //
	UserId    int64  `json:"user_id"`    //
}

//
type CcTopUpReq struct {
	Amount          string `json:"amount"`            //
	CardBin         string `json:"card_bin"`          //
	ClientId        int64  `json:"client_id"`         //
	ClientIp        string `json:"client_ip"`         // 访问者ip
	MerchantOrderNo string `json:"merchant_order_no"` //
	RefererUrl      string `json:"referer_url"`       // 上一个页面的url
	UserId          int64  `json:"user_id"`           //
}

//
type WithdrawalListRsp struct {
	Data  []WithdrawalListData `json:"data"`  //
	Total int64                `json:"total"` //
}

//
type TopUpIndexData struct {
	ActualAmount    int64  `json:"actual_amount"`     // ActualAmount 实际支付金额
	Amount          int64  `json:"amount"`            // Amount 订单金额
	ModeOfPay       string `json:"mode_of_pay"`       // Model 支付方式 merchant表里面支持的支付通道枚举类型的简称
	Status          int64  `json:"status"`            // Status 状态 :1 正在充值中 2:已完成 3:失败 4.已撤销
	UpdateTime      string `json:"update_time"`       //
	UserId          int64  `json:"user_id"`           // UserID 用户id
	Channel         string `json:"channel"`           // Channel 充值的具体通道
	CreateTime      string `json:"create_time"`       //
	Id              int64  `json:"id"`                //
	MerchantId      int64  `json:"merchant_id"`       // MerchantID 商户号
	MerchantOrderNo string `json:"merchant_order_no"` // MerchantOrderNo 商户订单编号
	OrderNo         string `json:"order_no"`          // OrderNo 系统订单编号
	ServeCharges    int64  `json:"serve_charges"`     // serve_charges 平台服务费
}

//
type TopUpIndexRsp struct {
	Data  []TopUpIndexData `json:"data"`  //
	Total int64            `json:"total"` //
}

//
type WalletPaymentRsp struct {
	OrderNo         string `json:"order_no"`          //
	Amount          int64  `json:"amount"`            //
	MerchantId      int64  `json:"merchant_id"`       //
	MerchantOrderNo string `json:"merchant_order_no"` //
}

//
type WithdrawalListData struct {
	Status                int64  `json:"status"`                  // Status 状态: 1 审核中 2:已完成 3:已拒绝 4:已取消
	WalletType            string `json:"wallet_type"`             // WalletType 钱包类型代号
	Fee                   int64  `json:"fee"`                     // Fee 手续费
	PayeeBankAccountNo    string `json:"payee_bank_account_no"`   // PayeeBankAccountNo 收款人银行卡号
	CreateTime            string `json:"create_time"`             //
	OperateTime           string `json:"operate_time"`            // OperateTime 审核人员操作时间
	PayeeIdentificationId string `json:"payee_identification_id"` // PayeeIdentificationID 收款人身份证号
	PayeeName             string `json:"payee_name"`              // PayeeName 收款人姓名
	UpdateTime            string `json:"update_time"`             //
	UserId                int64  `json:"user_id"`                 // UserID 用户id
	ClientId              int64  `json:"client_id"`               // ClientID 主商户id
	Id                    int64  `json:"id"`                      //
	OrderNo               string `json:"order_no"`                // OrderNo 系统订单编号
	PayeeBankName         string `json:"payee_bank_name"`         // PayeeBankName 收款人银行名称
	Amount                int64  `json:"amount"`                  // Amount 金额
}

//
type ChannelRecordStatListReq struct {
	Channel   string `json:"channel"`     // channel  支付通道
	EndTime   string `json:"end_time"`    //
	ModeOfPay string `json:"mode_of_pay"` // pay type 支付类型
	StartTime string `json:"start_time"`  //
}

//
type GetPrefundDetailRsp struct {
	List  []PrefundRecordsDetail `json:"list"`  //
	Total int64                  `json:"total"` //
}

//
type MerchantPayChannelListRspData struct {
	Item  []MerchantPayChannelItem `json:"item"`  //
	Total int64                    `json:"total"` //
}

//
type MerchantPayChannelListRsp struct {
	Code int64                         `json:"code"` //
	Data MerchantPayChannelListRspData `json:"data"` //
	Msg  string                        `json:"msg"`  //
	Time int64                         `json:"time"` //
}

//
type ChannelRecordStatListRsp struct {
	Total int64                   `json:"total"` //
	Data  []ChannelRecordStatData `json:"data"`  //
}

//
type FpxTopUpReq struct {
	BankCode        string `json:"bank_code"`         // bank code
	BankType        string `json:"bank_type"`         // bank type  01:b2c    02:b2b
	ClientIp        string `json:"client_ip"`         // 访问者ip
	MerchantOrderNo string `json:"merchant_order_no"` //
	RefererUrl      string `json:"referer_url"`       // 上一个页面的url
	Amount          string `json:"amount"`            //
	ClientId        int64  `json:"client_id"`         //
	NotifyUrl       string `json:"notify_url"`        //
	UserId          int64  `json:"user_id"`           //
}

//
type PaymentIndexData struct {
	ModeOfPay       string `json:"mode_of_pay"`       // Model 支付方式 merchant表里面支持的支付通道枚举类型
	IsRefund        int64  `json:"is_refund"`         // IsRefund 是否允许退款 1:允许 2不允许
	MerchantId      int64  `json:"merchant_id"`       // MerchantID 商户号(可能为主商户,子商户)
	Status          int64  `json:"status"`            // Status 状态 1 支付中 2:完成 3:失败 4.已撤销
	UpdateTime      string `json:"update_time"`       //
	UserId          int64  `json:"user_id"`           // UserID 用户id
	ActualAmount    int64  `json:"actual_amount"`     // ActualAmount 实际支付金额
	ClientId        int64  `json:"client_id"`         // ClientID 主商户id
	CreateTime      string `json:"create_time"`       //
	Id              int64  `json:"id"`                //
	Amount          int64  `json:"amount"`            // Amount 订单金额
	Fee             int64  `json:"fee"`               // Fee 手续费 mdr
	MerchantOrderNo string `json:"merchant_order_no"` // MerchantOrderNo 商户订单编号
	OrderNo         string `json:"order_no"`          // OrderNo 系统订单编号
}

//
type RefundListRsp struct {
	Total int64            `json:"total"` //
	Data  []RefundListData `json:"data"`  //
}

//
type WithdrawalAuditReq struct {
	DeclineReason string `json:"decline_reason"` // 拒绝原因
	Id            int64  `json:"id"`             //
	Status        int64  `json:"status"`         // Status 状态: 1 审核中 2:已完成 3:已拒绝 4:已取消
	AdminId       int64  `json:"admin_id"`       //
}

//
type WalletPaymentReq struct {
	Amount          string `json:"amount"`            // amount unit : cent
	ClientId        int64  `json:"client_id"`         //
	UserId          int64  `json:"user_id"`           //
	ClientIp        string `json:"client_ip"`         //
	MerchantId      int64  `json:"merchant_id"`       //
	MerchantOrderNo string `json:"merchant_order_no"` //
	Pin             string `json:"pin"`               // user pin code
	ProductName     string `json:"product_name"`      // product name 商品名称
	RefererUrl      string `json:"referer_url"`       //
}

//
type BaseResponseHeader struct {
	Code int64  `json:"code"` //
	Msg  string `json:"msg"`  //
	Time int64  `json:"time"` //
}

//
type OfflineDepositListReq struct {
	EndTime   string `json:"end_time"`   //
	PageNo    int64  `json:"page_no"`    //
	PageSize  int64  `json:"page_size"`  //
	StartTime string `json:"start_time"` //
	Status    int64  `json:"status"`     // Status 1 :pending 2:approve 3:decline
}

//
type PrefundRecords struct {
	MerchantId  string `json:"merchant_id"`  // MerchantID 商户编号/merchant id
	ReferenceId string `json:"reference_id"` // ReferenceID 参考编号/ change the amount reference no.
	TotalAmount int64  `json:"total_amount"` // Amount prefund 金额
}

//
type TopUpManualReq struct {
	OrderNo     string `json:"order_no"`      //
	AdminId     int64  `json:"admin_id"`      //
	Amount      string `json:"amount"`        //
	BankCode    string `json:"bank_code"`     //
	BankOrderNo string `json:"bank_order_no"` //
	BankTime    string `json:"bank_time"`     //
	Channel     string `json:"channel"`       //
}

//
type TransactionListRspWallet struct {
	Balance         string `json:"balance"`           //
	MaxBalanceLimit string `json:"max_balance_limit"` //
	Status          int64  `json:"status"`            // 1:active 2:suspend 3:termination
	Type            int64  `json:"type"`              // 1:base wallet  2:big wallet
}

//
type TransactionListRsp struct {
	Data   []TransactionListData    `json:"data"`   //
	Total  int64                    `json:"total"`  //
	Wallet TransactionListRspWallet `json:"wallet"` //
}

//
type CcDeleteCardReq struct {
	CardBin  string `json:"card_bin"`  //
	ClientId int64  `json:"client_id"` //
	UserId   int64  `json:"user_id"`   //
}

//
type RefundVoidReq struct {
	ClientIp        string `json:"client_ip"`         //
	MerchantId      int64  `json:"merchant_id"`       //
	MerchantOrderNo string `json:"merchant_order_no"` //
}

//
type CardList struct {
	Scheme       string `json:"scheme"`        // Card Scheme – Mastercard / Visa / Amex
	TopupEnabled int64  `json:"topup_enabled"` //
	ExpiryMonth  string `json:"expiry_month"`  //
	ExpiryYear   string `json:"expiry_year"`   //
	Reference    string `json:"reference"`     //
	SavedDate    string `json:"saved_date"`    //
	LastEnabled  int64  `json:"last_enabled"`  // Check the last enabled card. If enabled = 1, If not, it will be 0
	LastTopup    string `json:"last_topup"`    //
	MaskedPan    string `json:"masked_pan"`    // Card Number – Masked (First 6, Last 4)  523411XXXXXX0003
}

//
type ChannelItems struct {
	ModeOfPay string `json:"mode_of_pay"` //
}

//
type PaymentIndexRsp struct {
	Data  []PaymentIndexData `json:"data"`  //
	Total int64              `json:"total"` //
}

//
type RefundSummariesReq struct {
	MerchantId int64  `json:"merchant_id"` //
	PageNo     int64  `json:"page_no"`     //
	PageSize   int64  `json:"page_size"`   //
	StartTime  string `json:"start_time"`  //
	EndTime    string `json:"end_time"`    //
}

//
type OfflineDepositApplyReq struct {
	Amount   string `json:"amount"`    //
	ChequeNo string `json:"cheque_no"` // 支票号 cheque no
	Type     int64  `json:"type"`      // Type 1 :credit 2 debit
	UserId   int64  `json:"user_id"`   //
}

//
type OfflineDepositListRsp struct {
	Data  []OfflineDepositListData `json:"data"`  //
	Total int64                    `json:"total"` //
}

//
type PaymentIndexReq struct {
	StartTime       string `json:"start_time"`        //
	UserId          int64  `json:"user_id"`           // UserID 用户id
	PageNo          int64  `json:"page_no"`           //
	MerchantId      int64  `json:"merchant_id"`       // MerchantID 商户号
	MerchantOrderNo string `json:"merchant_order_no"` // MerchantOrderNo 商户订单编号
	OrderNo         string `json:"order_no"`          // OrderNo 系统订单编号
	PageSize        int64  `json:"page_size"`         //
	Status          int64  `json:"status"`            // Status 状态 :1 正在充值中 2:已完成 3:失败 4.已撤销
	EndTime         string `json:"end_time"`          //
}

//
type TransactionExceptionListRsp struct {
	Data  []TransactionExceptionListData `json:"data"`  //
	Total int64                          `json:"total"` //
}

//
type FpxTopUpRspData struct {
	FpxBuyerIban       string `json:"fpx_buyerIban"`       //
	FpxBuyerName       string `json:"fpx_buyerName"`       //
	FpxCheckSum        string `json:"fpx_checkSum"`        //
	FpxMakerName       string `json:"fpx_makerName"`       //
	FpxMsgType         string `json:"fpx_msgType"`         //
	FpxSellerOrderNo   string `json:"fpx_sellerOrderNo"`   //
	FpxTxnAmount       string `json:"fpx_txnAmount"`       //
	FpxBuyerAccNo      string `json:"fpx_buyerAccNo"`      //
	FpxBuyerEmail      string `json:"fpx_buyerEmail"`      //
	FpxProductDesc     string `json:"fpx_productDesc"`     //
	FpxSellerBankCode  string `json:"fpx_sellerBankCode"`  //
	FpxBuyerBankId     string `json:"fpx_buyerBankId"`     //
	FpxSellerTxnTime   string `json:"fpx_sellerTxnTime"`   //
	FpxTxnCurrency     string `json:"fpx_txnCurrency"`     //
	FpxBuyerId         string `json:"fpx_buyerId"`         //
	FpxMsgToken        string `json:"fpx_msgToken"`        //
	FpxSellerExId      string `json:"fpx_sellerExId"`      //
	FpxSellerExOrderNo string `json:"fpx_sellerExOrderNo"` //
	FpxSellerId        string `json:"fpx_sellerId"`        //
	FpxVersion         string `json:"fpx_version"`         //
	FpxBuyerBankBranch string `json:"fpx_buyerBankBranch"` //
}

//
type FpxTopUpRsp struct {
	Data FpxTopUpRspData `json:"data"` //
	Url  string          `json:"url"`  //
}

//
type GetPrefundRecordsRsp struct {
	List  []PrefundRecords `json:"list"`  //
	Total int64            `json:"total"` //
}

//
type PrefundRequest struct {
	WalletInfos []UserWalletInfo `json:"wallet_infos"` // PrefundMerchantID uint64           `json:"prefund_merchant_id"`
}

//
type RevertOrderSn struct {
	OrderSn string `json:"order_sn"` //
}

//
type GetPrefundRecordsDetailRequest struct {
	OrderSn      string `json:"order_sn"`      // OrderSn 用户订单号
	PageNo       int64  `json:"page_no"`       //
	PageSize     int64  `json:"page_size"`     //
	ReferenceId  string `json:"reference_id"`  // ReferenceID 参考编号/ change the amount reference no.
	RevertStatus int64  `json:"revert_status"` // RevertStatus revert 状态 1:unrevert 2:reverted
	UserId       int64  `json:"user_id"`       // UserID 用户id
	ClientId     int64  `json:"client_id"`     // MerchantID 商户编号/merchant id
}

//
type RefundAuditReq struct {
	RefundAgain   int64  `json:"refund_again"`   // maybe next time refund request : 1:yes  2:no
	Status        int64  `json:"status"`         // Status : 1:auditing 2:pass 3:complete 4:refuse  5:cancel
	ActualAmount  string `json:"actual_amount"`  // Approved refund amount 批准退款金额
	DeclineReason string `json:"decline_reason"` //
	Id            int64  `json:"id"`             //
}

//
type RefundCompleteReq struct {
	Id int64 `json:"id"` //
}

//
type RefundInfoRsp struct {
	ApplyAmount      int64  `json:"apply_amount"`       // ApplyAmount 申请退款金额
	IsRefundFee      int64  `json:"is_refund_fee"`      // IsRefundFee 是否退回手续费 1:no 2:yes
	MerchantId       int64  `json:"merchant_id"`        //
	OrderNo          string `json:"order_no"`           // OrderNo 退款订单编号
	ReasonForRefund  string `json:"reason_for_refund"`  // ReasonForRefund 退款原因
	RefundFee        int64  `json:"refund_fee"`         // RefundFee 退款手续费
	RefundHolderName string `json:"refund_holder_name"` // RefundHolderName 退款人姓名
	TradeNo          string `json:"trade_no"`           // TradeNo  关联的交易流水号
	ClientIp         string `json:"client_ip"`          // ClientIP 客户端ip
	DeclineReason    string `json:"decline_reason"`     // DeclineReason 拒绝原因
	RefundCardNo     string `json:"refund_card_no"`     // RefundCardNo 退款人卡号
	Remark           string `json:"remark"`             // Remark 备注
	Status           int64  `json:"status"`             // Status 状态: 1:审核中 2:审核通过 3:已完成 4:拒绝  5:已取消
	UpdateTime       string `json:"update_time"`        //
	WalletType       string `json:"wallet_type"`        // WalletType 钱包类型代号 默认主钱包 以后可能会扩展其他类型的钱包
	ActualAmount     int64  `json:"actual_amount"`      // ActualAmount 批准退款金额
	AdminId          int64  `json:"admin_id"`           // AdminID 审核人员id
	CreateTime       string `json:"create_time"`        //
	IsAuto           int64  `json:"is_auto"`            // IsAuto 是否自动退款: 1:否 2:是
	MerchantOrderNo  string `json:"merchant_order_no"`  // MerchantOrderNo 关联的商户支付订单号
	RefundBankName   string `json:"refund_bank_name"`   // RefundBankName 退款银行名称
	UserId           int64  `json:"user_id"`            //
	Id               int64  `json:"id"`                 //
	PaymentOrderNo   string `json:"payment_order_no"`   // PaymentOrderNo 关联的支付系统订单号
	RefundType       string `json:"refund_type"`        // RefundType 退款方式 merchant表里面支持的支付通道枚举类型
	WhoRefund        int64  `json:"who_refund"`         // WhoRefund 谁发起退款请求 1 :user 2:merchant 3:platform
}

//
type RefundListReq struct {
	PageSize        int64  `json:"page_size"`         //
	StartTime       string `json:"start_time"`        //
	Status          int64  `json:"status"`            // Status 1:Auditing  2:Pass 3:Completed 4:Refuse 5:Cancel
	EndTime         string `json:"end_time"`          //
	MerchantOrderNo string `json:"merchant_order_no"` //
	PageNo          int64  `json:"page_no"`           //
}

//
type TransactionExceptionListReq struct {
	PageSize        int64  `json:"page_size"`         //
	StartTime       string `json:"start_time"`        //
	Type            int64  `json:"type"`              // 1:zero fee  2:zero serve charge  3:more than 200  4:less than 5
	EndTime         string `json:"end_time"`          //
	MerchantOrderNo string `json:"merchant_order_no"` // merchant order no
	OrderNo         string `json:"order_no"`          //
	PageNo          int64  `json:"page_no"`           //
}

//
type UserWalletInfo struct {
	Money  int64 `json:"money"`   // @ApiModelProperty(value = "金额", required = true)
	UserId int64 `json:"user_id"` // @ApiModelProperty(value = "用户UUID", required = true)
}

//
type CcAddCardRsp struct {
	Url string `json:"url"` //
}

//
type CcCardListRsp struct {
	Primary          string     `json:"primary"`            // Enabled = 1, If not, it will be 0
	Threshold        int64      `json:"threshold"`          // Topup Threshold, returns 0.00 if not set
	TopupAmount      int64      `json:"topup_amount"`       //
	WalletId         string     `json:"wallet_id"`          //
	AutoTopupEnabled int64      `json:"auto_topup_enabled"` // Enabled = 1, if not, it will be 0. This value will be 1 if any of data.cards.topup_enabled value is 1.
	CardHolderName   string     `json:"card_holder_name"`   //
	Cards            []CardList `json:"cards"`              //
}

//
type GetPrefundRecordsRequest struct {
	ClientId    int64  `json:"client_id"`    // MerchantID 商户编号/merchant id
	PageNo      int64  `json:"page_no"`      //
	PageSize    int64  `json:"page_size"`    //
	ReferenceId string `json:"reference_id"` // ReferenceID 参考编号/ change the amount reference no.
}

//
type RevertRequest struct {
	OrderSns    []RevertOrderSn `json:"order_sns"`    //
	ReferenceId string          `json:"reference_id"` //
}

//
type TransactionExceptionListData struct {
	ActualAmount    int64  `json:"actual_amount"`     // ActualAmount 实际支付金额
	BankTime        string `json:"bank_time"`         // BankTime 银行实际交易时间
	MerchantId      int64  `json:"merchant_id"`       // MerchantID 商户号
	OrderNo         string `json:"order_no"`          // OrderNo 系统订单号
	TradeTime       string `json:"trade_time"`        // TradeTime 用户发起交易时间
	ClientId        int64  `json:"client_id"`         // ClientID 主商户id
	Fee             int64  `json:"fee"`               // Fee 手续费
	ServeCharges    int64  `json:"serve_charges"`     // serve_charges 平台服务费
	UserId          int64  `json:"user_id"`           // UserID 用户id
	ModeOfPay       string `json:"mode_of_pay"`       // ModeOfPayment 支付方式 merchant表里面支持的支付通道枚举类型
	TradeNo         string `json:"trade_no"`          // TradeNo 交易流水号
	WalletType      string `json:"wallet_type"`       // WalletType 钱包类型代号
	Amount          int64  `json:"amount"`            // Amount 订单金额 单位分
	BankAmount      int64  `json:"bank_amount"`       // BankAmount 银行返回的交易金额
	BankOrderNo     string `json:"bank_order_no"`     // BankOrderNo 银行订单流水号
	MerchantOrderNo string `json:"merchant_order_no"` // MerchantOrderNo 商户订单号
	Type            string `json:"type"`              // Type 交易类型 topup,payment,withdrawal等的简称
}

//
type PaymentWebV10RefundCompleteRequest struct {
	RefundCompleteReq RefundCompleteReq `json:"Param" in:"body"` // RefundCompleteReq
}

//
type PaymentWebV10RefundExcelRequest struct {
	RefundListReq RefundListReq `json:"Param" in:"body"` // RefundListReq
}

//
type PaymentWebV10TopupExcelRequest struct {
	TopUpIndexReq TopUpIndexReq `json:"Param" in:"body"` // Param
}

//
type PaymentWebV10TopupMerchantRequest struct {
	TopUpMerchantReq TopUpMerchantReq `json:"Param" in:"body"` // Param
}

//
type PaymentApiV10TopupCcRequest struct {
	CcTopUpReq CcTopUpReq `json:"Param" in:"body"` // Param
}

//
type PaymentWebV10ChannelStatIndexRequest struct {
	ChannelRecordStatListReq ChannelRecordStatListReq `json:"Param" in:"body"` // params
}

//
type PaymentWebV10MerchantWalletInfoRequest struct {
	MerchantWalletInfoReq MerchantWalletInfoReq `json:"Param" in:"body"` // MerchantWalletInfoReq
}

//
type PaymentWebV10PaymentExcelRequest struct {
	PaymentIndexReq PaymentIndexReq `json:"Param" in:"body"` // Param
}

//
type PaymentWebV10TopupIndexRequest struct {
	TopUpIndexReq TopUpIndexReq `json:"Param" in:"body"` // Param
}

//
type PaymentApiV10CardListRequest struct {
	CcCardListReq CcCardListReq `json:"Param" in:"body"` // Param
}

//
type PaymentApiV10RefundApplyRequest struct {
	RefundApplyReq RefundApplyReq `json:"Param" in:"body"` // RefundApplyReq
}

//
type PaymentWebV10RefundIndexRequest struct {
	RefundListReq RefundListReq `json:"Param" in:"body"` // RefundListReq
}

//
type PaymentWebV10RefundSummaryDownloadRequest struct {
	RefundSummariesReq RefundSummariesReq `json:"Param" in:"body"` // RefundSummariesReq
}

//
type PaymentApiV10TransactionIndexRequest struct {
	TransactionListReq TransactionListReq `json:"Param" in:"body"` // Param
}

//
type PaymentWebV10RefundApplyRequest struct {
	RefundApplyReq RefundApplyReq `json:"Param" in:"body"` // RefundCompleteReq
}

//
type PaymentWebV10RefundAuditRequest struct {
	RefundAuditReq RefundAuditReq `json:"Param" in:"body"` // RefundAuditReq
}

//
type PaymentWebV10PaymentIndexRequest struct {
	PaymentIndexReq PaymentIndexReq `json:"Param" in:"body"` // Param
}

//
type PaymentWebV10WithdrawalIndexRequest struct {
	WithdrawalListReq WithdrawalListReq `json:"Param" in:"body"` // Param
}

//
type PaymentApiV10CardDeleteRequest struct {
	CcDeleteCardReq CcDeleteCardReq `json:"Param" in:"body"` // Param
}

//
type PaymentApiV10RefundVoidRequest struct {
	RefundVoidReq RefundVoidReq `json:"Param" in:"body"` // RefundVoidReq
}

//
type PaymentApiV10TopupFpxRequest struct {
	FpxTopUpReq FpxTopUpReq `json:"Param" in:"body"` // Param
}

//
type PaymentApiV10WithdrawalApplyRequest struct {
	WithdrawalApplyReq WithdrawalApplyReq `json:"Param" in:"body"` // Param
}

//
type PaymentWebV10OfflineDepositAuditRequest struct {
	OfflineDepositAuditReq OfflineDepositAuditReq `json:"Param" in:"body"` // params
}

//
type PaymentWebV10OfflineDepositIndexRequest struct {
	OfflineDepositListReq OfflineDepositListReq `json:"Param" in:"body"` // params
}

//
type PaymentWebV10TransactionIndexRequest struct {
	TransactionListReq TransactionListReq `json:"Param" in:"body"` // Param
}

//
type PaymentWebV10WithdrawalAuditRequest struct {
	WithdrawalAuditReq WithdrawalAuditReq `json:"Param" in:"body"` // Param
}

//
type PaymentApiV10CardAddRequest struct {
	CcAddCardReq CcAddCardReq `json:"Param" in:"body"` // Param
}

//
type PaymentWebV10MerchantPrefundRequest struct {
	PrefundRequest PrefundRequest `json:"Param" in:"body"` // MerchantsRecharge
}

//
type PaymentWebV10MerchantPrefundHistoryRequest struct {
	GetPrefundRecordsRequest GetPrefundRecordsRequest `json:"Param" in:"body"` // GetPrefundRecordsRequest
}

//
type PaymentWebV10MerchantRevertRequest struct {
	RevertRequest RevertRequest `json:"Param" in:"body"` // MerchantsUserRecharge
}

//
type PaymentApiV10PaymentWalletRequest struct {
	WalletPaymentReq WalletPaymentReq `json:"Param" in:"body"` // WalletPaymentReq
}

//
type PaymentInnerV10CronChannelStatisticsYesterdayRequest struct {
}

//
type PaymentWebV10TopupManualRequest struct {
	TopUpManualReq TopUpManualReq `json:"Param" in:"body"` // Param
}

//
type PaymentInnerV10CronTopupTraceOrdersRequest struct {
}

//
type PaymentWebV10TransactionExcelRequest struct {
	TransactionListReq TransactionListReq `json:"Param" in:"body"` // Param
}

//
type PaymentWebV10TransactionExceptionListRequest struct {
	TransactionExceptionListReq TransactionExceptionListReq `json:"Param" in:"body"` // Param
}

//
type PaymentWebV10WithdrawalExcelRequest struct {
	WithdrawalListReq WithdrawalListReq `json:"Param" in:"body"` // Param
}

//
type PaymentWebV10RefundInfoRequest struct {
	Id int64 `json:"id" in:"query"` // refund id
}

//
type PaymentApiV10TransferTransferRequest struct {
	TransferReq TransferReq `json:"transferParam" in:"body"` // transferParam
}

//
type PaymentWebV10ChannelItemsRequest struct {
	ChannelItems ChannelItems `json:"Param" in:"body"` // params
}

//
type PaymentWebV10MerchantPrefundDetailRequest struct {
	GetPrefundRecordsDetailRequest GetPrefundRecordsDetailRequest `json:"Param" in:"body"` // GetTheMerchantsUserRecordsRequest
}

//
type PaymentWebV10OfflineDepositApplyRequest struct {
	OfflineDepositApplyReq OfflineDepositApplyReq `json:"Param" in:"body"` // params
}
